### ISSUE TITLE
Issue overwriting existing file

### ISSUE THREAD

**Issue by standage** [osfclient/osfclient#133]
The first time I execute the following command, it is successful.

```
osf --username myuser --project myproject upload myfile.dat myfile.dat
```

The second time I execute, I get the following error. Using the `--force` flag doesn't change the outcome.

<details>
  <summary>Click to expand</summary>

```
Traceback (most recent call last):
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/ssl.py", line 965, in sendall
    v = self.send(data[count:])
  File "/usr/lib64/python3.6/ssl.py", line 935, in send
    return self._sslobj.write(data)
  File "/usr/lib64/python3.6/ssl.py", line 636, in write
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/ssl.py", line 965, in sendall
    v = self.send(data[count:])
  File "/usr/lib64/python3.6/ssl.py", line 935, in send
    return self._sslobj.write(data)
  File "/usr/lib64/python3.6/ssl.py", line 636, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/standage/pico/env/bin/osf", line 11, in <module>
    sys.exit(main())
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/osfclient/__main__.py", line 104, in main
    exit_code = args.func(args)
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/osfclient/cli.py", line 91, in wrapper
    return_value = f(cli_args)
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/osfclient/cli.py", line 286, in upload
    store.create_file(remote_path, fp, update=args.force)
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/osfclient/models/storage.py", line 82, in create_file
    response = self._put(url, params={'name': fname}, data=fp)
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/osfclient/models/core.py", line 26, in _put
    return self.session.put(url, *args, **kwargs)
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/osfclient/models/session.py", line 37, in put
    response = super(OSFSession, self).put(url, *args, **kwargs)
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/requests/sessions.py", line 566, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/scratch/standage/pico/env/lib64/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
</details>

Any ideas? Is this a problem with the client or the server? Thanks!

**Comment by betatim** [comment]
Are you sure you get exactly the same error? When you try to upload a file that already exists you should get an error telling you that. If you don't that is a bug in the client for sure.

**Comment by standage** [comment]
Yes, it was precisely the same error message.

Oddly enough, this didn't happen yesterday on my Mac laptop. It was only a problem on a remote machine (Fedora). Both running osfclient 0.0.3 on Python 3.

**Comment by cmungall** [comment]
FWIW, I am experience the same issue, but only for larger files.

On smaller files, the behavior is as expected: the client gives me a `FileExistsError` message if `-f` is not set, and succeeds is `-f` is set.

However, when I try this on a larger file I see the same stacktrace as @standage. This suggests there is something different in the server behavior.

**Comment by cmungall** [comment]
OK, this shed some light on what's going on:

https://github.com/requests/requests/issues/2422

I believe that this code is never reached, since the server is closing the connection:

https://github.com/osfclient/osfclient/blob/cee05874c2596081f3a733fa010468305f862e12/osfclient/models/storage.py#L84

I'll try a patch...

**Comment by benlindsay** [comment]
I'm experiencing a very similar issue with ~25 MB files.
