### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by ljcohen** [osfclient/osfclient#137]
Hi! I'm trying to upload a file that is ~9GB from HPC to an osf project but keep getting this error. Am I doing something wrong?

```
[ljcohen@dev-intel14 ~]$ osf --version
osf 0.0.3
```
After running `export OSF_PASSWORD=password` and 
`export OSF_USERNAME=username`, here is the command followed by the error:
```
[ljcohen@dev-intel14 ~]$ osf -p zjv86 upload /mnt/scratch/ljcohen/onp_Porecamp_killifish/fastq2/porecamp_killifish_ONT_reads.fastq porecamp_killifish_ONT_reads.fastq
Traceback (most recent call last):
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 936, in _send_output
    self.send(message_body)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 905, in send
    self.sock.sendall(datablock)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/ssl.py", line 891, in sendall
    v = self.send(data[count:])
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 261, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 936, in _send_output
    self.send(message_body)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 905, in send
    self.sock.sendall(datablock)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/ssl.py", line 891, in sendall
    v = self.send(data[count:])
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home/ljcohen/.conda/envs/dammit/bin/osf", line 11, in <module>
    sys.exit(main())
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/osfclient/__main__.py", line 104, in main
    exit_code = args.func(args)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/osfclient/cli.py", line 91, in wrapper
    return_value = f(cli_args)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/osfclient/cli.py", line 286, in upload
    store.create_file(remote_path, fp, update=args.force)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/osfclient/models/storage.py", line 82, in create_file
    response = self._put(url, params={'name': fname}, data=fp)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/osfclient/models/core.py", line 26, in _put
    return self.session.put(url, *args, **kwargs)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/osfclient/models/session.py", line 37, in put
    response = super(OSFSession, self).put(url, *args, **kwargs)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/sessions.py", line 533, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

Other commands seem to work:
```
[ljcohen@dev-intel14 ~]$ osf -p zjv86 ls
osfstorage/kmer_genie/F_olivaceus-k31.histo
osfstorage/kmer_genie/F_olivaceus.dat
osfstorage/kmer_genie/F_olivaceus-k121.histo
osfstorage/kmer_genie/F_olivaceus.dat.pdf
osfstorage/kmer_genie/F_olivaceus-k111.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k101.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k115.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k113.histo
osfstorage/kmer_genie/F_olivaceus-k109.histo
osfstorage/kmer_genie/F_olivaceus-k115.histo
osfstorage/kmer_genie/F_olivaceus-k107.histo
osfstorage/kmer_genie/F_olivaceus-k91.histo
osfstorage/kmer_genie/F_olivaceus-k109.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k111.histo
osfstorage/kmer_genie/F_olivaceus-k117.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k117.histo
osfstorage/kmer_genie/F_olivaceus-k91.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k107.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k121.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k113.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k51.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k71.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k41.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k61.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k41.histo
osfstorage/kmer_genie/F_olivaceus-k21.histo
osfstorage/kmer_genie/F_olivaceus-k61.histo
osfstorage/kmer_genie/F_olivaceus-k31.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k81.histo
osfstorage/kmer_genie/F_olivaceus-k81.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k21.histo.pdf
osfstorage/kmer_genie/F_olivaceus-k71.histo
osfstorage/kmer_genie/F_olivaceus-k51.histo
osfstorage/kmer_genie/F_olivaceus_report.html
osfstorage/kmer_genie/F_olivaceus-k101.histo
...
```

**Comment by ljcohen** [comment]
Ah. I suspect this is an issue with my filesize limits, since the size of the file I'm trying to upload is >9GB. When I ran the same command with a smaller file, there was no error.

**Comment by benlindsay** [comment]
@ljcohen Yeah I think there's a 5 GB limit for a single file. Mind if we close this?

**Comment by ljcohen** [comment]
Please close! thank you.
