### ISSUE TITLE
RuntimeError: Response has status code 502 not (200,)

### ISSUE THREAD

**Issue by ljcohen** [osfclient/osfclient#141]
Not sure what this means, but looks possibly like a communication error with the server. I ran the command again and it seemed to upload the files completely on the second time. Documenting here in case something needs fixing?

```
ljcohen@js-168-9:~/O_fav/quant_Trinity$ osf -p sahnm upload -r hoc_ACTTGA_L007_R1_001_AD1HN0ACXX.filt.quant quant/
Traceback (most recent call last):
  File "/home/ljcohen/anaconda3/envs/dammit_new/bin/osf", line 11, in <module>
    sys.exit(main())
  File "/home/ljcohen/anaconda3/envs/dammit_new/lib/python3.6/site-packages/osfclient/__main__.py", line 104, in main
    exit_code = args.func(args)
  File "/home/ljcohen/anaconda3/envs/dammit_new/lib/python3.6/site-packages/osfclient/cli.py", line 91, in wrapper
    return_value = f(cli_args)
  File "/home/ljcohen/anaconda3/envs/dammit_new/lib/python3.6/site-packages/osfclient/cli.py", line 282, in upload
    store.create_file(name, fp, update=args.force)
  File "/home/ljcohen/anaconda3/envs/dammit_new/lib/python3.6/site-packages/osfclient/models/storage.py", line 73, in create_file
    parent = parent.create_folder(directory, exist_ok=True)
  File "/home/ljcohen/anaconda3/envs/dammit_new/lib/python3.6/site-packages/osfclient/models/file.py", line 135, in create_folder
    for folder in self.folders:
  File "/home/ljcohen/anaconda3/envs/dammit_new/lib/python3.6/site-packages/osfclient/models/file.py", line 101, in _iter_children
    children = self._follow_next(url)
  File "/home/ljcohen/anaconda3/envs/dammit_new/lib/python3.6/site-packages/osfclient/models/core.py", line 64, in _follow_next
    response = self._json(self._get(url), 200)
  File "/home/ljcohen/anaconda3/envs/dammit_new/lib/python3.6/site-packages/osfclient/models/core.py", line 60, in _json
    status_code))
RuntimeError: Response has status code 502 not (200,)
```

**Comment by felliott** [comment]
Hey @ljcohen,

I'm a dev at COS. We're currently experiencing some intermittent networking issues on our backend.  What you're seeing is a symptom of that.  Our DevOps team is busy trying to get it resolved.  In the meantime, we've put up a banner on the OSF to let our users know.  Once it's fixed we'll remove the banner and I'll post an update here.  Apologies for the inconvenience!

Cheers,
Fitz Elliott

P.S. I use a similar naming scheme for my virtualenvs! :smile:

**Comment by felliott** [comment]
Hey @ljcohen,

We think this has been resolved.  We'll keep an eye on it, but you should be able to upload reliably again.

Cheers,
Fitz

**Comment by ljcohen** [comment]
Thank you for your quick reply. I have not experienced this issue again since that day.

**Comment by jolespin** [comment]
@felliott @johnsolk what was the fix? I'm getting this now. 
https://github.com/osfclient/osfclient/issues/206
