### ISSUE TITLE
RuntimeError: Response has status code 504.

### ISSUE THREAD

**Issue by ljcohen** [osfclient/osfclient#164]
trying to clone a repository, error:
```
(ONT) johnsolk@barbera:~$ osf -p zjv86 clone
59files [11:54,  2.21s/files]
Traceback (most recent call last):####################################################################################################################################| 543/543 [00:00<00:00, 2.17Mbytes/s]
  File "/home/johnsolk/miniconda3/envs/ONT/bin/osf", line 11, in <module>
    sys.exit(main())
  File "/home/johnsolk/miniconda3/envs/ONT/lib/python3.7/site-packages/osfclient/__main__.py", line 104, in main
    exit_code = args.func(args)
  File "/home/johnsolk/miniconda3/envs/ONT/lib/python3.7/site-packages/osfclient/cli.py", line 91, in wrapper
    return_value = f(cli_args)
  File "/home/johnsolk/miniconda3/envs/ONT/lib/python3.7/site-packages/osfclient/cli.py", line 167, in clone
    file_.write_to(f)
  File "/home/johnsolk/miniconda3/envs/ONT/lib/python3.7/site-packages/osfclient/models/file.py", line 61, in write_to
    "code {}.".format(response.status_code))
RuntimeError: Response has status code 504.
```

**Comment by benlindsay** [comment]
@ljcohen I'm guessing there was just a server-side error because I'm cloning it on my computer just fine. I'll try with a python 3.7 environment and see if that affects anything (I'm on 3.6), but try again on your end to see if it was just a temporary server thing.

**Comment by ljcohen** [comment]
yes, than you - it downloaded after trying again. any way to prevent this from happening?

**Comment by benlindsay** [comment]
For now I don't think so...I think we need to work some smarter handling of some of these server side errors into the code.
