### ISSUE TITLE
RuntimeError: Response has status code 404 not (200,)

### ISSUE THREAD

**Issue by YuelinS** [osfclient/osfclient#168]
I just installed the osf client, but I always got this error when I tried basic commands, like this one:

```
(base) D:\>osf -p xxx<projectid> ls
Traceback (most recent call last):
File "D:\Applications\Anaconda\Scripts\osf-script.py", line 9, in <module>
   sys.exit(main())
File "D:\Applications\Anaconda\lib\site-packages\osfclient\__main__.py", line 104, in main
   exit_code = args.func(args)
File "D:\Applications\Anaconda\lib\site-packages\osfclient\cli.py", line 91, in wrapper
   return_value = f(cli_args)
File "D:\Applications\Anaconda\lib\site-packages\osfclient\cli.py", line 218, in list_
   project = osf.project(args.project)
File "D:\Applications\Anaconda\lib\site-packages\osfclient\api.py", line 24, in project
   return Project(self._json(self._get(url), 200), self.session)
File "D:\Applications\Anaconda\lib\site-packages\osfclient\models\core.py", line 60, in _json
   status_code))
RuntimeError: Response has status code 404 not (200,)
```

I installed and run it within an Anaconda enviroment, not sure if that's the reason?

**Comment by natemella** [comment]
I have the same exact error! I'm also running in an Anaconda environment

**Comment by natemella** [comment]
I hit the error even outside of the Anaconda environment

**Comment by natemella** [comment]
FSL:~ $ osf ls
Please input your password: 
Traceback (most recent call last):
  File "/fslhome/nmella/.local/bin/osf", line 10, in <module>
    sys.exit(main())
  File "/fslhome/nmella/.local/lib/python3.6/site-packages/osfclient/__main__.py", line 104, in main
    exit_code = args.func(args)
  File "/fslhome/nmella/.local/lib/python3.6/site-packages/osfclient/cli.py", line 91, in wrapper
    return_value = f(cli_args)
  File "/fslhome/nmella/.local/lib/python3.6/site-packages/osfclient/cli.py", line 218, in list_
    project = osf.project(args.project)
  File "/fslhome/nmella/.local/lib/python3.6/site-packages/osfclient/api.py", line 24, in project
    return Project(self._json(self._get(url), 200), self.session)
  File "/fslhome/nmella/.local/lib/python3.6/site-packages/osfclient/models/core.py", line 60, in _json
    status_code))
RuntimeError: Response has status code 404 not (200,)

**Comment by natemella** [comment]
I just found out that I hit this error because I wasn't using the correct project name. For example, look at the screen shot below. I originally was using the name of the project (TCGA Data Types Benchmark), but in reality I needed to use "3snep" which you can see in the url https://osf.io/3snep/
![image](https://user-images.githubusercontent.com/33582671/63452205-eefc4680-c402-11e9-8450-3f468f5dbc07.png)
