### ISSUE TITLE
KeyError: 'content-length' when cloning from OSF if Github-Add-on is activated

### ISSUE THREAD

**Issue by stebo85** [osfclient/osfclient#197]
Dear OSFclient team,

I hit a strange bug when trying to clone an OSF repo with a github add-on activated (osclient version 0.0.5 installed from pip): 

0files [00:05, ?files/s]
Traceback (most recent call last):
  File "/usr/local/bin/osf", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/osfclient/__main__.py", line 120, in main
    exit_code = args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/osfclient/cli.py", line 98, in wrapper
    return_value = f(cli_args)
  File "/usr/local/lib/python3.7/dist-packages/osfclient/cli.py", line 180, in clone
    file_.write_to(f)
  File "/usr/local/lib/python3.7/dist-packages/osfclient/models/file.py", line 61, in write_to
    int(response.headers['Content-Length']))
  File "/usr/local/lib/python3.7/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'

I deactivated the github-addon on OSF and the error disappeared. Any ideas what this could be?

The fetch command works ok, so my initial guess it that it trips over content in the git repo?

**Comment by famosab** [comment]
I observed the same error. Are there any news? I would really like to use the github addon!
